### ISSUE TITLE
第二章 nyc.json

### ISSUE THREAD

**Issue by Change72** [a8215965/MachineLearningBlueprints#2]
您好，可以分享一下 第二章 的 nyc.json 数据集吗？data下没有，自己找的不能用

**Comment by Relph1119** [comment]
我也没有这个数据集，在目录中有说，不好意思

**Comment by Change72** [comment]
http://data.beta.nyc//dataset/3bf5fb73-edb5-4b05-bb29-7c95f4a727fc/resource/6df127b1-6d04-4bb7-b983-07402a2c3f90/download/f4129d9aa6dd4281bc98d0f701629b76nyczipcodetabulationareas.geojson

我昨天用这个跑通了，效果还可以。

# threshold_scale=[1500.00, 1700.00, 1900.00, 2100.00, 2300.00, 2500.00, 2750.00, 4000.00],
但这个设定颜色区间的要注掉或者换成我上面的（因为有些房价不在原区间，会报错）

map.choropleth(geo_data='http://data.beta.nyc//dataset/3bf5fb73-edb5-4b05-bb29-7c95f4a727fc/resource/6df127b1-6d04-4bb7-b983-07402a2c3f90/download/f4129d9aa6dd4281bc98d0f701629b76nyczipcodetabulationareas.geojson', data=su_lt_two,
                  columns=['Zip', 'Rent'],
                  key_on='feature.properties.postalCode',
                  fill_color='YlOrRd',
                  # threshold_scale=[1500.00, 1700.00, 1900.00, 2100.00, 2300.00, 2500.00, 2750.00, 4000.00],
                  fill_opacity=0.7, line_opacity=0.2,
                  legend_name='Rent (%)',
                  reset=True
               )
